# Generated by Django 5.2.15 on 2026-06-09 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_alter_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='invited',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invited_by', to='referrals.telegramuser'),
        ),
    ]
